//
//  CreateOrderWorker.swift
//  CleanSwiftArchitecture
//
//  Created by Tshepo on 2017/08/01.
//  Copyright (c) 2017 none. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CreateOrderWorker
{
  func doSomeWork()
  {
  }
}
