//
//  CreateOrderPresenter.swift
//  CleanSwiftArchitecture
//
//  Created by Tshepo on 2017/08/01.
//  Copyright (c) 2017 none. All rights reserved.

//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderPresentationLogic
{
  func presentSomething(response: CreateOrder.Something.Response)
}

class CreateOrderPresenter: CreateOrderPresentationLogic
{
  weak var viewController: CreateOrderDisplayLogic?
  
  //MARK: Do something
  
  func presentSomething(response: CreateOrder.Something.Response)
  {
    
    var roundedvalue = response.nextlevel
    
    let viewModel = CreateOrder.Something.ViewModel(newvalue:roundedvalue.roundToPlaces(2))
    // presentation of a value

    viewController?.displaySomething(viewModel: viewModel)
  }
    
    
    
    
}
extension Double {
    /// Rounds the double to decimal places value
    mutating func roundToPlaces(_ places:Int) -> Double {
        let divisor = pow(10.0, Double(places))
        return Darwin.round(self * divisor) / divisor
    }
}
